Feature 4 - done
eels911/AndroidAcademy pull request #8
Opened 2021-07-06 12:09 UTC by eels911

2021-07-06 12:29 UTC, konovalov-k requested changes

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/ActorListAdapter.kt
> +        return ViewHolderActor(inflater.inflate(R.layout.item_actor, parent, false))
Вынеси в переменную тк не ясн что это лайоут

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +    var movies: List<Movie>,
Перенести в переменную класса из конструктора

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +    var movies: List<Movie>,
notifyDataSetChanged()

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/FragmentMoviesList.kt
> +        MoviesAdapter(requireContext(), generateMovies(requireContext()), movieDetails)
сетить фильмы из метода адаптера

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/FragmentMoviesList.kt
> +                .add(R.id.main, FragmentMoviesDetails(movie))
Через arguments pзакинуть в Bundle

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/FragmentMoviesDetails.kt
> +class FragmentMoviesDetails (private var movie: Movie) : Fragment(R.layout.fragment_movies_details) {
убрать из конструктора фильмы

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +           itemView.setOnClickListener(this)
val clickListener = object : View.OnClickListener {
//onclick logic
}

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +    interface OnMovieListener {
Можно снести если не используешь

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +    interface OnMovieListener {
val someFun: ()-> Unit = { }

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/res/layout/fragment_movies_list.xml
> +    android:layout_width="match_parent"
убрать ConstrainLAyout оставить родительским RecyclerView

2021-07-06 12:29 UTC, konovalov-k commented on lesson4/src/main/res/layout/item_movie.xml
> +    <View
Сделай красиво cmd + L

2021-07-07 15:21 UTC, eels911 commented on lesson4/src/main/java/com/example/lesson4/MoviesAdapter.kt
> +    var movies: List<Movie>,
notifyDataSetChanged() в updateData?

2021-07-15 10:24 UTC, merged